### ISSUE TITLE
Test chunk issue

### ISSUE THREAD

**Issue by ImanMh** [flowjs/flow-php-server#11]
When I enable ```testChunks``` optsion in my JS script, I get a 404 error but when I set it to false it works just fine, what am I doing wrong?

**Comment by AidasK** [comment]
404 means that file was not found on the server. Js script just sends a check request to make sure that file was not uploaded previously and `flow-php-server` responds 404 if it is not.

**Comment by ImanMh** [comment]
Correct me if I'm wrong, this error message means that the file was not previously uploaded and I can safely start my upload without errors.
If it is true, why the file is not uploaded when I set ```testChunks``` to true.

**Comment by AidasK** [comment]
File should be uploaded on a second request if testChunks request returned
status 404. If status was 200, file won't be uploaded.

**Comment by ImanMh** [comment]
I see a 404 error in my browser console but Flow.js does not try to upload the file after that. Do I need to change any option to get it working? 
here is my code:
```javascript
var f = new Flow({
  target:'upload.php',
  chunkSize: 1024*1024,
  testChunks: true
});
```
the error callback gets called but it doesn't try to upload the file.

**Comment by AidasK** [comment]
Make sure that 404 error comes from flow-php-server library and not from
http server (make sure upload.php exists).

**Comment by ImanMh** [comment]
I'm sure because when I change it to  ```testChunks: false``` it works just fine.

**Comment by AidasK** [comment]
Can you see in the network GET and POST requests? What are the response
codes to the POST request?

**Comment by ImanMh** [comment]
I expected an other request after 404

![screen shot 1393-11-12 at 14 54 34](https://cloud.githubusercontent.com/assets/4482199/5991905/57ae022c-aa22-11e4-939c-c58a7dbf6969.png)

**Comment by AidasK** [comment]
Maybe there are some logged errors in the console?

**Comment by ImanMh** [comment]
every thing works as expected, all the event handlers are functioning and this is my 404 error. 
![screen shot 1393-11-12 at 18 23 01](https://cloud.githubusercontent.com/assets/4482199/5992444/e859788e-aa3f-11e4-9c94-065007765084.png)

**Comment by AidasK** [comment]
Try returning 204 status instead of 404, it should solve your problem. I will make a change in `flow-php-server` that it would use `204` by default. It seems `flow.js` is not working with default configuration with a server since 2.8.0 release. `404` status in test handler is considered a permanent error.

Thanks for your patience.

**Comment by ImanMh** [comment]
I returned a 204 header and it works now. Thank you for all your attention.
