### ISSUE TITLE
[Question] How to read additional query parameters server side

### ISSUE THREAD

**Issue by npx** [flowjs/flow-php-server#19]
Hey there,

and thank you for the great work on this library.

Using ng-flow I am uploading images and it works quite nicely (using a Laravel 5 backend).

So far I managed to get around adding additional query parameters, but now I need them. Using the "query" parameter in the configuration of ng-flow I am adding an additional value that is sent to the server correctly.

However, I just cannot find a way on the server side to read my additional parameter.
I'm sorry but I just cannot find it :/

**Comment by Nemeth050506** [comment]
I would like to know how we could read the query values on the serverside if we are using jus plain PHP

**Comment by channaveer** [comment]
You can set it with **query** config

```
var flow = new Flow({
    /** Other settings */
    query: { '_token' : '{{ csrf_token() }}', 'greeting' : 'hello' } /* Add your additional params to pass here */
});
```
