### ISSUE TITLE
Can not find package

### ISSUE THREAD

**Issue by be-codified** [flowjs/flow-php-server#24]
Hi,

I am using

    composer require flowjs/flow-php-server

and getting following notice

    [InvalidArgumentException]
    Could not find package flowjs/flow-php-server at any version for your minimum-stability (stable). 
    Check the package spelling or your minimum-stability

What could be wrong?

**Comment by AidasK** [comment]
Is this issue still valid?

**Comment by be-codified** [comment]
Still. Can you provide some help?

**Comment by AidasK** [comment]
Could you show your entire composer config?

**Comment by be-codified** [comment]
{
		"name": "laravel/laravel",
		"description": "The Laravel Framework.",
		"keywords": ["framework", "laravel"],
		"license": "MIT",
		"type": "project",
		"require": {
			"laravel/framework": "5.0.*",
			"way/generators": "^3.0"
		},
		"require-dev": {
			"phpunit/phpunit": "~4.0",
			"phpspec/phpspec": "~2.1",
			"laracasts/generators": "^1.1",
			"fzaninotto/faker": "^1.4",
			"guzzlehttp/guzzle": "~5.0",
	        "h4cc/wkhtmltopdf-amd64": "0.12.x",
	        "h4cc/wkhtmltoimage-amd64": "0.12.x",
			"barryvdh/laravel-snappy": "0.2.x"
		},
		"autoload": {
			"classmap": [
				"database"
			],
			"psr-4": {
				"App\\": "app/"
			}
		},
		"autoload-dev": {
			"classmap": [
				"tests/TestCase.php"
			]
		},
		"scripts": {
			"post-install-cmd": [
				"php artisan clear-compiled",
				"php artisan optimize"
			],
			"post-update-cmd": [
				"php artisan clear-compiled",
				"php artisan optimize"
			],
			"post-create-project-cmd": [
				"php -r \"copy('.env.example', '.env');\"",
				"php artisan key:generate"
			]
		},
		"config": {
			"preferred-install": "dist"
		}
	}

**Comment by AidasK** [comment]
Tried and it works for me. Maybe you should delete vendor dir and composer.lock files?

**Comment by be-codified** [comment]
Ah, it also worked for me. I guess I was trying to run composer outside of my virtual machine.

Thank you for your effort.

**Comment by letitechera** [comment]
(Just an input, in case anyone is interested) For those getting this error without working with virtual machines, running cmd console as administrator solves the problem :)

**Comment by letitechera** [comment]
(Just an input, in case anyone is interested) For those getting this error without working with virtual machines, running cmd console as administrator solves the problem :)
