### ISSUE TITLE
update mongo from legacy mongo lib to mongodb/mongodb

### ISSUE THREAD

**Issue by daniel-sc** [flowjs/flow-php-server#48]
the current implementation is based on the obsolete mongo lib.
this should be changed to mongodb/mongodb.
I'd be willing to provide a PR :)

**Comment by AidasK** [comment]
sure, please do

**Comment by borakayalar** [comment]
I wait, I hope @AidasK updates it. Also I need basic implemantion code with "$yourGridFs"

**Comment by AidasK** [comment]
Maybe @daniel-sc could help? It looks he was the latest dev to use this store.

**Comment by borakayalar** [comment]
Thanks @AidasK , @daniel-sc, I wait your response I hope you help me :)

**Comment by daniel-sc** [comment]
@AidasK This issue should be closed as it was resolved with #49 

@borakayalar usage should be straight forward, as constructor parameter is typed to `MongoDB\GridFS\Bucket` (see https://github.com/flowjs/flow-php-server/blob/master/src/Flow/Mongo/MongoConfig.php#L18). In case you are not up to date wrt the php mongo drivers: https://www.mongodb.com/docs/php-library/v1.15/
