### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by Acorath** [flowjs/flow-php-server#5]
I'm currently working on a project which uses flow.js and flow-php-server.

9 times out of 10, when uploading the same 5mb PDF it transfers fine.  However, sometimes it will arrive corrupted.  A successful transfer would have a mime-type of "application/pdf", the corrupt transfers have a mime-type of "application/octet-stream".

I'm not sure if the root of the corruption is on the client or server side.  Let me know what info you need and I'll pull together what I can.

**Comment by dkarter** [comment]
I have this issue as well: simultaneous pdf uploads appear to work but the files arrive corrupted, sometimes it works and sometimes doesn't.

**Comment by devcodebakerz** [comment]
This issue seems to be because of difference of loop types while saving and merging. While saving the for loop is decremental and while merging it was an incremental for loop. So I don't see any traction on this issue, how can I submit ? or can I even submit ?

**Comment by AidasK** [comment]
I think this is issue of unsupported windows os or ruby implementation so it can be closed.
