### ISSUE TITLE
PHP 8.4 support?

### ISSUE THREAD

**Issue by phpfui** [flowjs/flow-php-server#52]
I would be happy to add PHP 8.4 support, but there are issues.

First, we would need to drop support for any version below 7.1, since that is when nullable types were introduced.  There are only two minor changes to support PHP 8.4, constructors in Basic and File need nullable types. Usage of PHP below 7.1 is virtual non-existant. Also those users can continue to use the existing version.

Also I think we should convert to GitHub Actions and drop Travis CI.

Let me know if this makes sense.

**Comment by AidasK** [comment]
Makes sense, please do! You can drop all suport for 7.*, it's outdated anyways.

**Comment by phpfui** [comment]
Awesome. Thanks. So many maintainers are not responding.

**Comment by phpfui** [comment]
I am getting this when running tests in two places:
```
Error: Call to undefined method Unit\FustyRequestTest::getMock()
```

Any ideas what I should replace this with?  I don't see it referenced in the git history either, so not sure how it ever worked.

**Comment by phpfui** [comment]
Apparently getMock is from PHPUnit, but now called createMock.  Closing as there is now a PR to review.
